- name: Checking deploy directory exists...
  stat: path={{ deploy_path }}
  register: deploy_exists
  become: true

- name: Removing deploy directory...
  command: rm -r "{{ deploy_path }}"
  become: true
  when: deploy_exists.stat.exists
