- name: Creating deployment directory
  file: path={{ deploy_path }}
        state=directory
        owner=monitor
        group=rpi-group
  become: true

- name: Creating logs directory
  file: path={{ deploy_path }}/logs
        state=directory
        owner=monitor
        group=rpi-group
        mode=775
  become: true

- name:     Copying shared configuration,
  include:  ../../common/tasks/copyOnRemote.yml
            src="{{ temp_path }}/config/"
            dest="{{ deploy_path }}/config/"
            owner="monitor"
            group="rpi-group"
            perms="775"
  become:   true

- name:     Copying website override files,
  include:  ../../common/tasks/copyOnRemote.yml
            src="{{ temp_path }}/website/"
            dest="{{ deploy_path }}/website/"
            owner="monitor"
            group="rpi-group"
            perms="775"
  become:   true
