- name: Copying Screen Daemon JAR
  copy: src={{ screen_daemon }}/target/screen-daemon-1.0.jar dest={{ deploy_path }} mode=0777

- {
    name:         Setting Up Screen Daemon,
    include:      ../../common/tasks/setupService.yml,
    service_name: "screen-daemon",
    daemon_name:  "screen-daemon"
  }
