- name: Stopping ntp service
  service:  name=ntp
            state=stopped
  become: true

- name: Forcing ntpupdate...
  shell:  ntpdate pool.ntp.org
  ignore_errors: true
  become: true

- name: Starting ntp service
  service:  name=ntp
            state=stopped
  become: true

# Disabled since this may not work behind a corporate network, and thus just slow down the Pi
#- {
#    name:         Setting up automatic time sync on boot,
#    include:      ../../common/tasks/setupService.yml,
#    service_name: "pi-sync-time"
#  }
