- name: Updating apt-get cache
  apt:  update_cache=yes
  become: true

- name: Upgrading entire OS
  apt:  upgrade=full
  become: true

- name: Installing rsync
  apt:  name=rsync
        state=present
  become: true

- name: Installing sudo
  apt:  name=sudo
        state=present
  become: true

- name: Installing mDNS for hostname resolution
  apt:  name=avahi-daemon
        state=present
  become: true

- name: Installing Oracle JDK 8
  apt:  name=oracle-java8-jdk
        state=present
  become: true

- name: Installing htop
  apt:  name=htop
        state=present
  become: true

- name: Installing dnsutils
  apt:  name=dnsutils
        state=present
  become: true

- name: Installing ntp
  apt:  name=ntp
        state=present
  become: true

- name: Installing ntupdate
  apt:  name=ntpdate
        state=present
  become: true

