- name: Creating backup directory
  file: path={{ backup_path }}
        state=directory
        owner=monitor
        group=rpi-group
        mode=775
  sudo: true

- name: Checking deploy directory exists
  stat: path={{ deploy_path }}
  register: deploy_exists
  sudo: true

- name: Checking logs directory exists
  stat: path={{ deploy_path }}/logs
  register: logs_exist
  sudo: true

- name: Fetching date time string
  shell: date "+%Y-%m-%d_%H-%M-%S"
  register: backup_datetime

- name: Removing logs directory
  command: rm -r "{{ deploy_path }}/logs"
  sudo: true
  when: logs_exist.stat.exists

- name:     Creating backup of previous deployment
  include:  ../../common/tasks/copyOnRemote.yml
            src="{{ deploy_path }}/"
            dest="{{ backup_path }}/{{ backup_datetime.stdout }}/"
            owner="monitor"
            group="rpi-group"
            perms="775"
  sudo:     true
  when:     deploy_exists.stat.exists
