- name: Creating managed user for wallboard
  user: name=wallboard
        state=present
        shell=/bin/bash
        comment="Account for displaying wallboard"
        createhome=yes
        append=no
        groups=rpi-group
  sudo: true

- name: Installing X11 utils for xset
  apt:  name=x11-xserver-utils
        state=present
  when: nopackages is not defined
  sudo: true

- name: Installing Matchbox window manager
  apt:  name=matchbox-desktop
        state=present
  when: nopackages is not defined
  sudo: true

- name: Installing Chromium browser
  apt:  name=chromium-browser
        state=present
  when: nopackages is not defined
  sudo: true

- {
      name:         Setting up .xinitrc for wallboard user,
      include:      ../../common/tasks/copyOnRemote.yml,

      src:          "{{ temp_path }}/wallboard/.xinitrc",
      dest:         "/home/wallboard/.xinitrc",
      owner:        "wallboard",
      group:        "wallboard",
      perms:        "755",
      sudo:         true,
  }

- name: Setting up automatic login of wallboard user
  shell: "{{ temp_path }}/setup-scripts/automatic-login.sh wallboard"
  sudo: true

- name: Disabling blanking of monitor
  shell: "{{ temp_path }}/setup-scripts/disable-blanking.sh"
  sudo: true

- name: Setting up bashrc to run x11
  shell: "{{ temp_path }}/setup-scripts/setup-bashrc-x11.sh"
  sudo: true
