- name: Copying remote daemon JAR
  copy: src={{ remote_daemon }}/target/remote-daemon.jar
        dest={{ deploy_path }}
        mode=0770
        owner=rpi-daemon
        group=rpi-group
  become: true

- {
    name:         Setting Up Remote Daemon,
    include:      ../../common/tasks/setupService.yml,
    service_name: "remote-daemon"
  }
