- name: Copying system daemon JAR
  copy: src={{ system_daemon }}/target/system-daemon.jar
        dest={{ deploy_path }}
        mode=0770
        owner=rpi-daemon
        group=rpi-group
  become: true

- {
    name:         Setting Up System Daemon,
    include:      ../../common/tasks/setupService.yml,
    service_name: "system-daemon"
  }

- name: Installing cec library (screen on/off)
  apt:  name=libcec3
        state=present
  become: true

- name: Installing cec utils (screen on/off)
  apt:  name=cec-utils
        state=present
  become: true
