- name: Removing previous temp files (in case of failure last run)
  command: rm -R {{ files_dest }}
  ignore_errors: true
  sudo: true

- name: Copying base files
  copy: src="{{ files_base }}/"
        dest="{{ files_dest }}"
        mode="0777"
  sudo: true

- name: Copying override base files
  copy: src="{{ files_override }}/{{ override_base }}/"
          dest="{{ files_dest }}"
          mode="0777"
  sudo: true
  when: files_override is defined and override_base is defined

- name: Copying override files
  copy: src="{{ files_override }}/{{ inventory_hostname }}/"
        dest="{{ files_dest }}"
        mode="0777"
  sudo: true
  when: files_override is defined and hostname_override is not defined

- name: Copying override files (hostname override)
  copy: src="{{ files_override }}/{{ hostname_override }}/"
        dest="{{ files_dest }}"
        mode="0777"
  sudo: true
  when: files_override is defined and hostname_override is defined
