- name: Check if Service Already Exists
  stat: path=/etc/init.d/{{service_name}}
  register: service_status

- name: Stopping Service
  service: name={{service_name}} state=stopped
  when: service_status.stat.exists
  register: service_stopped

- name: Copying Service File to init.d
  copy: src="../../{{daemon_name}}/files/{{service_name}}" dest="/etc/init.d/{{service_name}}" mode=0777
  sudo: true

- name: Registering Service
  shell: "update-rc.d {{service_name}} defaults"
  sudo: true

- name: Starting Service
  shell: "service {{service_name}} start"
  sudo: true
