- name: Checking if service already exists...
  stat: path=/etc/init.d/{{service_name}}
  register: service_status

- name: Stopping service...
  service: name={{service_name}} state=stopped
  when: service_status.stat.exists
  register: service_stopped

- name: Copying service file to init.d
  command: cp "{{ temp_path }}/daemons/{{ service_name }}" "/etc/init.d/{{service_name}}"
  become: true

- name: Registering Service
  shell: "update-rc.d {{service_name}} defaults"
  become: true

- name: Starting Service
  shell: "service {{service_name}} start"
  become: true
