- name: Creating backup directory
  file: path={{ backup_path }}
        state=directory
        owner=monitor
        group=rpi-group
        mode=775
  sudo: true

- name: Checking deploy directory exists
  stat: path={{ deploy_path }}
  register: deploy_exists
  sudo: true

- name: Checking logs directory exists
  stat: path={{ deploy_path }}/logs
  register: logs_exist
  sudo: true

- name: Removing logs directory
  command: rm -r "{{ deploy_path }}/logs"
  sudo: true
  when: logs_exist.stat.exists

- {
      name:         Creating backup of previous deployment,
      include:      ../../common/tasks/copyOnRemote.yml,

      src:          "{{ deploy_path }}/",
      dest:         "{{ backup_path }}/{{ ansible_date_time.date }}_{{ ansible_date_time.time }}/",
      owner:        "monitor",
      group:        "rpi-group",
      perms:        "775",
      sudo:         true,
      when:         deploy_exists.stat.exists
  }
